import os

from backend.main import (
    GenerateRequest,
    generate_content,
    extract_json_from_text,
    validate_llm_content,
)


class DummyChatCompletion:
    @staticmethod
    def create(**kwargs):
        return {
            "choices": [
                {
                    "message": {
                        "content": (
                            "```json\n"
                            "{\n"
                            "  \"reel_script\": \"Hook: This is a test. Body: Create an influencer asset. CTA: Follow now.\",\n"
                            "  \"linkedin_post\": \"This is a professional LinkedIn post.\",\n"
                            "  \"instagram_caption\": \"A catchy caption #brand #marketing #influencer #growth #social\"\n"
                            "}\n```"
                        )
                    }
                }
            ]
        }


class InvalidChatCompletion:
    @staticmethod
    def create(**kwargs):
        return {"choices": [{"message": {"content": "This is invalid output, not JSON."}}]}


def test_extract_json_from_markdown_wrapped_text():
    text = "```json\n{\"reel_script\":\"hello\",\"linkedin_post\":\"hi\",\"instagram_caption\":\"hello #tag1 #tag2 #tag3 #tag4 #tag5\"}\n```"
    parsed = extract_json_from_text(text)
    assert parsed is not None
    assert parsed["reel_script"] == "hello"
    assert parsed["instagram_caption"].startswith("hello")


def test_validate_llm_content_rejects_empty_or_missing_fields():
    assert validate_llm_content({"reel_script": "", "linkedin_post": "hi", "instagram_caption": "caption"}) is None
    assert validate_llm_content({"reel_script": "script", "linkedin_post": "", "instagram_caption": "caption"}) is None
    assert validate_llm_content({"reel_script": "script", "linkedin_post": "post"}) is None


def test_generate_content_parses_valid_llm_json(monkeypatch):
    import backend.main as main_mod

    monkeypatch.setenv("OPENAI_API_KEY", "test-api-key")
    main_mod.OPENAI_API_KEY = "test-api-key"
    monkeypatch.setattr(main_mod, "openai", type("DummyOpenAI", (), {"ChatCompletion": DummyChatCompletion}))

    response = generate_content(GenerateRequest(topic_title="Test topic"))
    assert response.success is True
    assert response.content is not None
    assert response.content["reel_script"].startswith("Hook:")
    assert response.assets["reelScript"] is True
    assert response.message == "Content generated by LLM."


def test_generate_content_fallback_when_llm_output_invalid(monkeypatch):
    import backend.main as main_mod

    monkeypatch.setenv("OPENAI_API_KEY", "test-api-key")
    main_mod.OPENAI_API_KEY = "test-api-key"
    monkeypatch.setattr(main_mod, "openai", type("DummyOpenAI", (), {"ChatCompletion": InvalidChatCompletion}))

    response = generate_content(GenerateRequest(topic_title="Test topic"))
    assert response.success is True
    assert response.content is not None
    assert response.content["reel_script"].startswith("[Fallback]")
    assert response.assets["reelScript"] is True
    assert response.assets["instagramCaption"] is True
    assert "fallback" in response.message.lower()
