import type { BrandProfile, InfluencerProfile } from "./types";

export const influencers: InfluencerProfile[] = [
  {
    id: "inf-001",
    name: "Aanya Verma",
    handle: "@aanya.skin",
    category: "Beauty",
    nicheTags: ["clean beauty", "skincare", "routine", "wellness"],
    location: "Mumbai, India",
    languages: ["English", "Hindi"],
    audience: {
      age: [
        { label: "18-24", share: 0.42 },
        { label: "25-34", share: 0.36 },
        { label: "35-44", share: 0.16 },
        { label: "45+", share: 0.06 },
      ],
      gender: [
        { label: "female", share: 0.74 },
        { label: "male", share: 0.22 },
        { label: "nonbinary", share: 0.04 },
      ],
      topRegions: ["India", "UAE", "UK"],
      interests: ["dermatology", "skin health", "self care", "luxury"],
    },
    metrics: {
      followers: 1280000,
      following: 840,
      avgLikes: 62000,
      avgComments: 1800,
      avgShares: 4200,
      avgSaves: 5200,
      avgViews: 310000,
      postsPerWeek: 4.1,
      avgWatchTimeSec: 9.4,
    },
    growth: {
      followerGrowth30d: 0.08,
      engagementGrowth30d: 0.05,
      audienceExpansion30d: 0.04,
    },
    quality: {
      purchasedFollowersScore: 0.08,
      engagementPodScore: 0.1,
      botActivityScore: 0.12,
      spikeScore: 0.15,
      commentQuality: 0.82,
      audienceQuality: 0.88,
    },
  },
  {
    id: "inf-002",
    name: "Kiran West",
    handle: "@coachkiran",
    category: "Fitness",
    nicheTags: ["strength", "training", "sports nutrition", "recovery"],
    location: "Austin, USA",
    languages: ["English"],
    audience: {
      age: [
        { label: "18-24", share: 0.32 },
        { label: "25-34", share: 0.44 },
        { label: "35-44", share: 0.18 },
        { label: "45+", share: 0.06 },
      ],
      gender: [
        { label: "female", share: 0.48 },
        { label: "male", share: 0.49 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["USA", "Canada", "UK"],
      interests: ["gym", "nutrition", "performance", "mobility"],
    },
    metrics: {
      followers: 880000,
      following: 520,
      avgLikes: 51000,
      avgComments: 1100,
      avgShares: 5800,
      avgSaves: 7100,
      avgViews: 280000,
      postsPerWeek: 5.2,
      avgWatchTimeSec: 12.3,
    },
    growth: {
      followerGrowth30d: 0.12,
      engagementGrowth30d: 0.09,
      audienceExpansion30d: 0.08,
    },
    quality: {
      purchasedFollowersScore: 0.05,
      engagementPodScore: 0.06,
      botActivityScore: 0.05,
      spikeScore: 0.08,
      commentQuality: 0.86,
      audienceQuality: 0.9,
    },
  },
  {
    id: "inf-003",
    name: "Milo Park",
    handle: "@milo.gg",
    category: "Gaming",
    nicheTags: ["esports", "streaming", "fps", "gear"],
    location: "Seoul, South Korea",
    languages: ["Korean", "English"],
    audience: {
      age: [
        { label: "18-24", share: 0.48 },
        { label: "25-34", share: 0.36 },
        { label: "35-44", share: 0.12 },
        { label: "45+", share: 0.04 },
      ],
      gender: [
        { label: "female", share: 0.28 },
        { label: "male", share: 0.69 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["South Korea", "Japan", "USA"],
      interests: ["competitive gaming", "hardware", "streaming"],
    },
    metrics: {
      followers: 620000,
      following: 310,
      avgLikes: 39000,
      avgComments: 2500,
      avgShares: 6200,
      avgSaves: 2200,
      avgViews: 420000,
      postsPerWeek: 6.3,
      avgWatchTimeSec: 14.8,
    },
    growth: {
      followerGrowth30d: 0.16,
      engagementGrowth30d: 0.14,
      audienceExpansion30d: 0.12,
    },
    quality: {
      purchasedFollowersScore: 0.04,
      engagementPodScore: 0.08,
      botActivityScore: 0.09,
      spikeScore: 0.1,
      commentQuality: 0.78,
      audienceQuality: 0.84,
    },
  },
  {
    id: "inf-004",
    name: "Sana Noor",
    handle: "@sana.travels",
    category: "Travel",
    nicheTags: ["slow travel", "luxury stays", "photography", "city guides"],
    location: "Dubai, UAE",
    languages: ["English", "Arabic"],
    audience: {
      age: [
        { label: "18-24", share: 0.26 },
        { label: "25-34", share: 0.46 },
        { label: "35-44", share: 0.2 },
        { label: "45+", share: 0.08 },
      ],
      gender: [
        { label: "female", share: 0.62 },
        { label: "male", share: 0.35 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["UAE", "UK", "Italy"],
      interests: ["luxury", "hotels", "culture", "photography"],
    },
    metrics: {
      followers: 1950000,
      following: 1200,
      avgLikes: 74000,
      avgComments: 1400,
      avgShares: 3600,
      avgSaves: 9400,
      avgViews: 510000,
      postsPerWeek: 3.0,
      avgWatchTimeSec: 11.1,
    },
    growth: {
      followerGrowth30d: 0.05,
      engagementGrowth30d: 0.03,
      audienceExpansion30d: 0.02,
    },
    quality: {
      purchasedFollowersScore: 0.18,
      engagementPodScore: 0.14,
      botActivityScore: 0.2,
      spikeScore: 0.22,
      commentQuality: 0.62,
      audienceQuality: 0.7,
    },
  },
  {
    id: "inf-005",
    name: "Rhea Kale",
    handle: "@rhea.cooks",
    category: "Food",
    nicheTags: ["home cooking", "meal prep", "recipes", "comfort food"],
    location: "Pune, India",
    languages: ["English", "Marathi"],
    audience: {
      age: [
        { label: "18-24", share: 0.3 },
        { label: "25-34", share: 0.43 },
        { label: "35-44", share: 0.2 },
        { label: "45+", share: 0.07 },
      ],
      gender: [
        { label: "female", share: 0.61 },
        { label: "male", share: 0.36 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["India", "Singapore", "Australia"],
      interests: ["food", "meal prep", "kitchen tools"],
    },
    metrics: {
      followers: 420000,
      following: 410,
      avgLikes: 28000,
      avgComments: 820,
      avgShares: 2100,
      avgSaves: 6800,
      avgViews: 180000,
      postsPerWeek: 4.7,
      avgWatchTimeSec: 10.2,
    },
    growth: {
      followerGrowth30d: 0.09,
      engagementGrowth30d: 0.07,
      audienceExpansion30d: 0.06,
    },
    quality: {
      purchasedFollowersScore: 0.07,
      engagementPodScore: 0.05,
      botActivityScore: 0.06,
      spikeScore: 0.08,
      commentQuality: 0.81,
      audienceQuality: 0.86,
    },
  },
  {
    id: "inf-006",
    name: "Dev Shah",
    handle: "@dev.invests",
    category: "Fintech",
    nicheTags: ["personal finance", "investing", "startups", "productivity"],
    location: "London, UK",
    languages: ["English"],
    audience: {
      age: [
        { label: "18-24", share: 0.22 },
        { label: "25-34", share: 0.48 },
        { label: "35-44", share: 0.22 },
        { label: "45+", share: 0.08 },
      ],
      gender: [
        { label: "female", share: 0.38 },
        { label: "male", share: 0.59 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["UK", "USA", "Germany"],
      interests: ["saving", "investing", "fintech"],
    },
    metrics: {
      followers: 260000,
      following: 260,
      avgLikes: 9600,
      avgComments: 520,
      avgShares: 2400,
      avgSaves: 4400,
      avgViews: 90000,
      postsPerWeek: 2.1,
      avgWatchTimeSec: 8.6,
    },
    growth: {
      followerGrowth30d: 0.1,
      engagementGrowth30d: 0.12,
      audienceExpansion30d: 0.1,
    },
    quality: {
      purchasedFollowersScore: 0.03,
      engagementPodScore: 0.03,
      botActivityScore: 0.04,
      spikeScore: 0.05,
      commentQuality: 0.9,
      audienceQuality: 0.92,
    },
  },
  {
    id: "inf-007",
    name: "Jules Hart",
    handle: "@jules.style",
    category: "Fashion",
    nicheTags: ["street style", "capsule wardrobe", "luxury", "styling"],
    location: "Paris, France",
    languages: ["French", "English"],
    audience: {
      age: [
        { label: "18-24", share: 0.34 },
        { label: "25-34", share: 0.4 },
        { label: "35-44", share: 0.18 },
        { label: "45+", share: 0.08 },
      ],
      gender: [
        { label: "female", share: 0.7 },
        { label: "male", share: 0.27 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["France", "Italy", "USA"],
      interests: ["fashion", "luxury", "design"],
    },
    metrics: {
      followers: 1100000,
      following: 980,
      avgLikes: 42000,
      avgComments: 1000,
      avgShares: 2700,
      avgSaves: 4900,
      avgViews: 260000,
      postsPerWeek: 3.5,
      avgWatchTimeSec: 9.1,
    },
    growth: {
      followerGrowth30d: 0.06,
      engagementGrowth30d: 0.04,
      audienceExpansion30d: 0.03,
    },
    quality: {
      purchasedFollowersScore: 0.11,
      engagementPodScore: 0.12,
      botActivityScore: 0.13,
      spikeScore: 0.15,
      commentQuality: 0.72,
      audienceQuality: 0.78,
    },
  },
  {
    id: "inf-008",
    name: "Theo Gupta",
    handle: "@theo.tech",
    category: "Tech",
    nicheTags: ["gadgets", "ai", "product reviews", "productivity"],
    location: "Toronto, Canada",
    languages: ["English"],
    audience: {
      age: [
        { label: "18-24", share: 0.28 },
        { label: "25-34", share: 0.45 },
        { label: "35-44", share: 0.2 },
        { label: "45+", share: 0.07 },
      ],
      gender: [
        { label: "female", share: 0.34 },
        { label: "male", share: 0.63 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["Canada", "USA", "India"],
      interests: ["technology", "productivity", "ai"],
    },
    metrics: {
      followers: 510000,
      following: 380,
      avgLikes: 21000,
      avgComments: 980,
      avgShares: 3200,
      avgSaves: 5100,
      avgViews: 170000,
      postsPerWeek: 3.8,
      avgWatchTimeSec: 13.7,
    },
    growth: {
      followerGrowth30d: 0.14,
      engagementGrowth30d: 0.13,
      audienceExpansion30d: 0.11,
    },
    quality: {
      purchasedFollowersScore: 0.04,
      engagementPodScore: 0.05,
      botActivityScore: 0.04,
      spikeScore: 0.06,
      commentQuality: 0.88,
      audienceQuality: 0.9,
    },
  },
  {
    id: "inf-009",
    name: "Maya Brooks",
    handle: "@maya.earth",
    category: "Sustainability",
    nicheTags: ["climate", "eco living", "ethical brands", "community"],
    location: "Portland, USA",
    languages: ["English"],
    audience: {
      age: [
        { label: "18-24", share: 0.33 },
        { label: "25-34", share: 0.41 },
        { label: "35-44", share: 0.18 },
        { label: "45+", share: 0.08 },
      ],
      gender: [
        { label: "female", share: 0.66 },
        { label: "male", share: 0.31 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["USA", "Netherlands", "Germany"],
      interests: ["sustainability", "climate", "ethical shopping"],
    },
    metrics: {
      followers: 360000,
      following: 290,
      avgLikes: 18000,
      avgComments: 1200,
      avgShares: 4500,
      avgSaves: 6000,
      avgViews: 210000,
      postsPerWeek: 4.4,
      avgWatchTimeSec: 12,
    },
    growth: {
      followerGrowth30d: 0.11,
      engagementGrowth30d: 0.1,
      audienceExpansion30d: 0.09,
    },
    quality: {
      purchasedFollowersScore: 0.05,
      engagementPodScore: 0.04,
      botActivityScore: 0.05,
      spikeScore: 0.07,
      commentQuality: 0.86,
      audienceQuality: 0.89,
    },
  },
  {
    id: "inf-010",
    name: "Leo Chen",
    handle: "@leo.sonic",
    category: "Music",
    nicheTags: ["indie", "studio", "live sessions", "songwriting"],
    location: "Los Angeles, USA",
    languages: ["English", "Mandarin"],
    audience: {
      age: [
        { label: "18-24", share: 0.41 },
        { label: "25-34", share: 0.37 },
        { label: "35-44", share: 0.16 },
        { label: "45+", share: 0.06 },
      ],
      gender: [
        { label: "female", share: 0.52 },
        { label: "male", share: 0.45 },
        { label: "nonbinary", share: 0.03 },
      ],
      topRegions: ["USA", "Mexico", "Philippines"],
      interests: ["music", "live shows", "vinyl"],
    },
    metrics: {
      followers: 740000,
      following: 420,
      avgLikes: 36000,
      avgComments: 1900,
      avgShares: 7200,
      avgSaves: 3800,
      avgViews: 390000,
      postsPerWeek: 5,
      avgWatchTimeSec: 15.2,
    },
    growth: {
      followerGrowth30d: 0.13,
      engagementGrowth30d: 0.15,
      audienceExpansion30d: 0.12,
    },
    quality: {
      purchasedFollowersScore: 0.06,
      engagementPodScore: 0.09,
      botActivityScore: 0.08,
      spikeScore: 0.1,
      commentQuality: 0.8,
      audienceQuality: 0.85,
    },
  },
];

export const brands: BrandProfile[] = [
  {
    id: "brand-001",
    name: "GlowAura Skincare",
    industry: "Beauty",
    tone: "clean, clinical, premium",
    targetAudience: ["women 18-34", "skin health", "self care"],
    keywords: ["serum", "spf", "glow", "skincare", "routine"],
    brandValues: ["science led", "inclusive", "luxury"],
    budgetTier: "premium",
  },
  {
    id: "brand-002",
    name: "StrideFuel",
    industry: "Fitness",
    tone: "high energy, performance",
    targetAudience: ["gym goers", "runners", "strength athletes"],
    keywords: ["protein", "recovery", "strength", "mobility"],
    brandValues: ["performance", "safety", "results"],
    budgetTier: "premium",
  },
  {
    id: "brand-003",
    name: "Nebula Gear",
    industry: "Gaming",
    tone: "bold, competitive",
    targetAudience: ["esports", "streamers", "pc builders"],
    keywords: ["fps", "headset", "keyboard", "streaming"],
    brandValues: ["speed", "precision", "community"],
    budgetTier: "enterprise",
  },
  {
    id: "brand-004",
    name: "Wanderly Luggage",
    industry: "Travel",
    tone: "cinematic, aspirational",
    targetAudience: ["frequent travelers", "digital nomads"],
    keywords: ["luggage", "hotel", "city guide", "luxury"],
    brandValues: ["craft", "comfort", "style"],
    budgetTier: "premium",
  },
  {
    id: "brand-005",
    name: "CrispKitchen",
    industry: "Food",
    tone: "warm, practical",
    targetAudience: ["home cooks", "meal prep", "busy families"],
    keywords: ["recipes", "meal prep", "kitchen tools"],
    brandValues: ["ease", "comfort", "quality"],
    budgetTier: "mid",
  },
  {
    id: "brand-006",
    name: "VaultWise",
    industry: "Fintech",
    tone: "trusted, smart",
    targetAudience: ["young professionals", "investors"],
    keywords: ["saving", "investing", "budgeting", "fintech"],
    brandValues: ["trust", "transparency", "education"],
    budgetTier: "enterprise",
  },
  {
    id: "brand-007",
    name: "Loom and Loop",
    industry: "Fashion",
    tone: "artful, luxe",
    targetAudience: ["style seekers", "luxury buyers"],
    keywords: ["capsule", "styling", "street style", "luxury"],
    brandValues: ["craft", "design", "modern"],
    budgetTier: "premium",
  },
  {
    id: "brand-008",
    name: "CircuitLab",
    industry: "Tech",
    tone: "futurist, analytical",
    targetAudience: ["creators", "early adopters"],
    keywords: ["gadgets", "ai", "productivity", "reviews"],
    brandValues: ["innovation", "clarity", "trust"],
    budgetTier: "premium",
  },
  {
    id: "brand-009",
    name: "EverEarth",
    industry: "Sustainability",
    tone: "purpose driven",
    targetAudience: ["eco shoppers", "climate advocates"],
    keywords: ["eco living", "ethical", "climate", "community"],
    brandValues: ["impact", "transparency", "community"],
    budgetTier: "mid",
  },
  {
    id: "brand-010",
    name: "PulseWave Records",
    industry: "Music",
    tone: "indie, energetic",
    targetAudience: ["music fans", "live events"],
    keywords: ["live sessions", "studio", "songwriting", "vinyl"],
    brandValues: ["creativity", "culture", "artists first"],
    budgetTier: "mid",
  },
];

export const getInfluencers = (): InfluencerProfile[] => influencers;

export const getBrands = (): BrandProfile[] => brands;
